name: Check sveltejs/kit repo for new commits

on:
  schedule:
    - cron:  '0 3 * * *'

jobs:
  track-commits:
    runs-on: ubuntu-latest
    name: Checking for new commits...
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Check for new commits in sveltejs/kit
      uses: AlexxNB/track-commits-to-issue@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        owner: sveltejs
        repo: kit
        dir: documentation